export const PHONE = '970-456-3666'
export const PHONE_HREF = 'tel:+19704563666'
export const LOCATION = 'Aspen, Colorado'

export const rvaData = {
  name: 'Rich Valley Adventures',
  tagline: 'Discover the Heart of Aspen',
  description: 'Since 2012, Rich Valley Adventures has been dedicated to protecting and sharing the beauty of Aspen and the Roaring Fork Valley through guided outdoor experiences that create lasting memories.',
  phone: PHONE, phoneHref: PHONE_HREF, location: LOCATION,
  logo: '/images/logos/rva-logo.png',
  email: 'kit@richvalleyadventures.com',
  social: {
    facebook: 'https://www.facebook.com/richvalleyadventures',
    instagram: 'https://www.instagram.com/richvalleyadventures',
  },
  stats: [
    { value: '14+', label: 'Years of Experience' },
    { value: '3,000+', label: 'Adventures Led' },
    { value: '4.9', label: 'Average Rating' },
  ],
  adventures: [
    { title: 'Fly Fishing', slug: 'fly-fishing', description: 'Wade into pristine mountain streams with expert guides who know every pool and riffle in the Roaring Fork Valley. All equipment provided.', image: '/images/adventures/fly-fishing.png', duration: 'Half Day / Full Day', difficulty: 'All Levels', season: 'summer' as const },
    { title: 'Paddle Boarding', slug: 'paddle-boarding', description: 'Glide across crystal-clear alpine lakes with stunning mountain backdrops. Perfect for families and first-timers.', image: '/images/adventures/paddle-boarding.jpg', duration: '2–3 Hours', difficulty: 'Beginner Friendly', season: 'summer' as const },
    { title: 'Mountain Biking', slug: 'mountain-biking', description: 'Explore world-class singletrack and scenic trails through aspen groves and alpine meadows.', image: '/images/adventures/mountain-biking.jpg', duration: 'Half Day / Full Day', difficulty: 'All Levels', season: 'summer' as const },
    { title: 'Trail Hiking', slug: 'trail-hiking', description: 'Discover hidden waterfalls, wildflower meadows, and panoramic summit views with guides who bring the ecology and history of the Rockies to life.', image: '/images/adventures/hiking.png', duration: '3–6 Hours', difficulty: 'Moderate', season: 'summer' as const },
    { title: 'Scenic Escalade Tours', slug: 'scenic-escalade-tours', description: "See Colorado's most iconic landmarks from the comfort of a luxury Escalade. Perfect for those who want the views without the vertical.", image: '/images/adventures/scenic-escalade.png', duration: 'Half Day / Full Day', difficulty: 'Easy — Ride Along', season: 'year-round' as const },
    { title: 'Horseback Riding', slug: 'horseback-riding', description: 'Experience the Rockies the way the first settlers did — on horseback. Gentle trail rides through meadows and aspen forests.', image: '/images/adventures/horseback-riding.png', duration: '2–4 Hours', difficulty: 'All Levels', season: 'summer' as const },
    { title: 'Elevated Camping', slug: 'elevated-camping', description: 'Glamping meets wilderness. Premium basecamp with gourmet meals, comfortable sleeping, and guided night-sky viewing.', image: '/images/adventures/elevated-camping.jpeg', duration: 'Overnight / Multi-Day', difficulty: 'All Levels', season: 'summer' as const },
  ],
  winterAdventures: [
    { title: 'Snowshoeing', slug: 'snowshoeing', description: 'Explore pristine backcountry trails through snow-covered aspen groves and alpine meadows. Our guides lead you through some of the most beautiful winter landscapes in the Rockies.', image: '/images/adventures/hiking.png', duration: '2–4 Hours', difficulty: 'All Levels' },
    { title: 'Cross-Country Skiing', slug: 'cross-country-skiing', description: 'Glide through groomed trails and backcountry routes with expert instruction. Equipment provided for all skill levels.', image: '/images/adventures/mountain-biking.jpg', duration: 'Half Day / Full Day', difficulty: 'All Levels' },
    { title: 'Ice Fishing', slug: 'ice-fishing', description: 'Experience the stillness of a frozen alpine lake. Our guides set up everything — warm shelter, gear, and hot drinks — while you wait for the big catch.', image: '/images/adventures/fly-fishing.png', duration: 'Half Day', difficulty: 'All Levels' },
    { title: 'Winter Escalade Tours', slug: 'winter-escalade-tours', description: 'See the Roaring Fork Valley blanketed in snow from the warmth of a luxury Escalade. Visit Maroon Bells, Independence Pass viewpoints, and charming mountain towns.', image: '/images/adventures/scenic-escalade.png', duration: 'Half Day / Full Day', difficulty: 'Easy — Ride Along' },
  ],
  whyChooseUs: [
    { title: 'Local Expertise', description: 'Born and raised in the valley. Our guides know every trail, stream, and hidden gem.' },
    { title: 'All-Inclusive Gear', description: 'Premium equipment included with every adventure. Just show up.' },
    { title: 'Small Groups', description: 'Intimate experiences, not cattle calls. Personalized attention on every trip.' },
    { title: 'Safety First', description: 'Wilderness first-aid certified guides, comprehensive insurance, meticulous protocols.' },
  ],
  testimonials: [
    { quote: "My wife and I had such a great time fishing with Kit. He under-promised, over-delivered and all the while kept us comfortable and smiling. We can't wait for our next Rich Valley Adventure!", name: 'Mike Kensington', location: 'Raleigh, NC' },
    { quote: "Since Rich Valley Adventures offers a wide range of activities, our family was able to go on three different amazing trips during our week in Aspen.", name: 'Zola Richards', location: 'Omaha, NE' },
  ],
  gallery: [
    '/images/adventures/fly-fishing.png', '/images/adventures/paddle-boarding.jpg', '/images/adventures/mountain-biking.jpg',
    '/images/adventures/hiking.png', '/images/adventures/elevated-camping.jpeg', '/images/adventures/horseback-riding.png',
    '/images/adventures/fly-fishing-action.jpeg', '/images/adventures/paddle-boarding-lake.png', '/images/adventures/fishing-catch.jpeg',
  ],
  partnerSite: {
    name: 'Aspen Alpenglow Limousine',
    description: 'Need a ride to the trailhead — or anywhere else? Our sister company offers luxury transportation with the same personal touch.',
    url: 'https://aspenalpenglowlimosine.com',
  },
}

export const alpenglowData = {
  name: 'Aspen Alpenglow Limousine',
  tagline: 'Luxury Transportation in the Roaring Fork Valley',
  description: 'Since 2012, Aspen Alpenglow Limousine has provided distinguished private car and limousine service throughout Aspen, Snowmass, and the Roaring Fork Valley. Available 24/7.',
  phone: PHONE, phoneHref: PHONE_HREF, location: LOCATION,
  logo: '/images/logos/alpenglow-logo.png',
  email: 'kit@richvalleyadventures.com',
  social: {
    facebook: 'https://www.facebook.com/aspenalpenglow',
    instagram: 'https://www.instagram.com/aspenalpenglow',
  },
  stats: [
    { value: '24/7', label: 'Dispatch Available' },
    { value: '14+', label: 'Years of Service' },
    { value: '4.9', label: 'Client Rating' },
  ],
  services: [
    { title: 'Airport Transfers', slug: 'airport-transfers', description: "Seamless door-to-door service to and from ASE and EGE airports. Real-time flight tracking ensures we're there when you land.", features: ['Flight tracking & meet-and-greet', 'Complimentary wait time', 'Luggage assistance', '24/7 dispatch'], icon: 'Plane' },
    { title: 'Hourly Charter', slug: 'hourly-charter', description: 'Your vehicle, your schedule. Book by the hour for shopping, dining, scenic drives, or any occasion.', features: ['Flexible scheduling', 'Multiple stop itineraries', 'Complimentary refreshments', 'Professional chauffeur'], icon: 'Clock' },
    { title: 'Corporate Travel', slug: 'corporate-travel', description: 'Make the right impression. Reliable, discreet transportation for executives, clients, and teams.', features: ['Corporate account billing', 'Confidential & professional', 'Competitive group rates', 'Licensed & fully insured'], icon: 'Briefcase' },
    { title: 'Wedding Transportation', slug: 'wedding-transportation', description: 'Your day deserves perfect logistics. Bridal party shuttles to grand getaway cars.', features: ['Custom itinerary planning', 'Bridal party coordination', 'Decorated vehicles available', 'Package discounts'], icon: 'Heart' },
  ],
  fleet: [
    { name: 'Executive Escalade', image: '/images/fleet/escalade.png', passengers: 'Up to 6 Passengers', features: ['Premium leather interior', 'Climate control', 'USB & WiFi', 'Privacy partition available'] },
    { name: 'Luxury Sprinter', image: '/images/fleet/sprinter.png', passengers: 'Up to 14 Passengers', features: ['Executive seating', 'Entertainment system', 'Overhead storage', 'Standing headroom'] },
  ],
  serviceAreas: [
    { name: 'Aspen', slug: 'aspen', description: 'Downtown, Aspen Mountain, Aspen Highlands' },
    { name: 'Snowmass Village', slug: 'snowmass-village', description: 'Base Village, Snowmass Ski Area' },
    { name: 'Basalt & El Jebel', slug: 'basalt', description: 'Mid-valley convenience' },
    { name: 'Carbondale', slug: 'carbondale', description: 'Crystal Valley, Redstone, Marble' },
    { name: 'Glenwood Springs', slug: 'glenwood-springs', description: 'Hot springs, I-70 corridor' },
    { name: 'Eagle / Vail', slug: 'eagle-vail', description: 'EGE airport, Vail Valley connections' },
    { name: 'Denver', slug: 'denver', description: 'Denver International Airport (DEN) transfers' },
    { name: 'Rifle', slug: 'rifle', description: 'Rifle Falls, I-70 western corridor' },
  ],
  destinations: [
    { name: 'Garden of the Gods', image: '/images/destinations/garden-of-the-gods.jpg', description: 'Stunning red rock formations in Colorado Springs — a must-see on any Colorado road trip.' },
    { name: 'Denver Botanic Gardens', image: '/images/destinations/denver-botanic-gardens.jpg', description: 'World-class botanical gardens in the heart of Denver with seasonal exhibits.' },
    { name: 'Red Rocks Amphitheatre', image: '/images/destinations/red-rocks.jpg', description: 'Iconic open-air concert venue set among dramatic red sandstone formations.' },
    { name: 'Coors Field', image: '/images/destinations/coors-field.jpg', description: 'Home of the Colorado Rockies — catch a game with luxury transportation.' },
    { name: 'Pikes Peak', image: '/images/destinations/pikes-peak.jpg', description: "America's Mountain at 14,115 feet — breathtaking views of the Front Range." },
  ],
  testimonials: [
    { quote: 'Absolutely first-class service. The Escalade was immaculate, and they tracked our delayed flight without us even asking.', name: 'James & Patricia Holden', location: 'Dallas, TX' },
    { quote: 'We hired Alpenglow for our wedding weekend and they were flawless — shuttles ran on time, the bridal car was gorgeous.', name: 'Sarah Mehta', location: 'Denver, CO' },
  ],
  whyChooseUs: [
    { title: 'Flight Tracking', description: 'We monitor your flight in real-time so your ride is waiting, even if plans change.' },
    { title: 'Local Knowledge', description: 'Our drivers live here. They know the fastest routes and the valley inside out.' },
    { title: 'Impeccable Fleet', description: 'Late-model luxury vehicles, professionally detailed before every ride.' },
    { title: 'White-Glove Service', description: 'Meet-and-greet, luggage handling, complimentary refreshments — every detail covered.' },
  ],
  partnerSite: {
    name: 'Rich Valley Adventures',
    description: "Looking for something to do while you're in town? Our sister company offers guided fly fishing, paddle boarding, mountain biking, and more.",
    url: 'https://richvalleyadventures.com',
  },
}

export const photoNotes = {
  rvaHero: { current: '/images/about/hero.jpg', note: 'Hero image from original site.' },
  alpenglowHero: { current: '/images/about/pexels-outdoor.png', note: 'Hero image for Alpenglow.' },
  teamPhoto: { current: '/images/about/founder-kit.jpeg', note: 'Founder Kit photo.' },
}

// Gallery image paths for seeding
export const galleryImages = [
  { path: '/images/gallery/bzp1131.jpg', alt: 'Rich Valley Adventures outdoor experience' },
  { path: '/images/gallery/bzp1795.jpg', alt: 'Aspen mountain adventure' },
  { path: '/images/gallery/img_65121.jpeg', alt: 'Fly fishing in Roaring Fork Valley' },
  { path: '/images/gallery/img_4071.jpeg', alt: 'Guided outdoor adventure' },
  { path: '/images/gallery/family-hike.jpg', alt: 'Family hiking adventure in Aspen' },
  { path: '/images/gallery/img_4226-3863d226.jpeg', alt: 'Fly fishing action shot' },
  { path: '/images/gallery/kids-fishing.jpeg', alt: 'Kids fly fishing trip in Roaring Fork Valley' },
  { path: '/images/gallery/img_4330.jpeg', alt: 'Mountain adventure experience' },
  { path: '/images/gallery/img_1721.jpeg', alt: 'Scenic mountain view' },
  { path: '/images/gallery/img_6142.jpg', alt: 'River fishing adventure' },
  { path: '/images/gallery/img_6117.jpeg', alt: 'Outdoor guided experience' },
  { path: '/images/gallery/rva-web-photos3.png', alt: 'Rich Valley Adventures team' },
  { path: '/images/gallery/img_1627.jpeg', alt: 'Mountain trail experience' },
  { path: '/images/gallery/fullsizerender.jpeg', alt: 'Adventure in the Rockies' },
  { path: '/images/gallery/img_0494.jpeg', alt: 'Guided mountain experience' },
  { path: '/images/gallery/dsc02480.jpeg', alt: 'Scenic Colorado landscape' },
  { path: '/images/gallery/img_6161.jpeg', alt: 'Fishing catch in Aspen' },
  { path: '/images/gallery/img_4450-fda81333.jpeg', alt: 'River fly fishing' },
  { path: '/images/gallery/img_8761.jpeg', alt: 'Mountain bike trail' },
  { path: '/images/gallery/img_6038.jpeg', alt: 'Roaring Fork Valley adventure' },
  { path: '/images/gallery/dsc00536.jpeg', alt: 'Aspen wilderness experience' },
  { path: '/images/gallery/bike-tour.jpeg', alt: 'Mountain bike tour in Aspen' },
  { path: '/images/gallery/img_1092.jpeg', alt: 'Guided hiking in Elk Mountains' },
  { path: '/images/gallery/img_6683.jpeg', alt: 'Adventure in the valley' },
  { path: '/images/gallery/bzp1124.jpg', alt: 'Professional outdoor photography' },
  { path: '/images/gallery/bzp11311.jpg', alt: 'Mountain scenery' },
  { path: '/images/gallery/bzp1136.jpg', alt: 'Aspen mountain view' },
  { path: '/images/gallery/bzp1139.jpg', alt: 'Valley panorama' },
  { path: '/images/gallery/bzp1144.jpg', alt: 'Outdoor adventure moment' },
  { path: '/images/gallery/bzp1146.jpg', alt: 'Mountain trail view' },
  { path: '/images/gallery/bzp1149.jpg', alt: 'Rocky Mountain scenery' },
  { path: '/images/gallery/bzp1154.jpg', alt: 'Aspen grove trail' },
  { path: '/images/gallery/bzp1159.jpg', alt: 'Mountain adventure' },
  { path: '/images/gallery/bzp1162.jpg', alt: 'Wilderness exploration' },
  { path: '/images/gallery/bzp1177.jpg', alt: 'Roaring Fork River' },
  { path: '/images/gallery/bzp1188-pano.jpg', alt: 'Panoramic mountain view' },
  { path: '/images/gallery/bzp1189.jpg', alt: 'Alpine meadow' },
  { path: '/images/gallery/bzp1190.jpg', alt: 'Mountain landscape' },
  { path: '/images/gallery/bzp1231.jpg', alt: 'Guided expedition' },
  { path: '/images/gallery/bzp1232.jpg', alt: 'Mountain adventure moment' },
  { path: '/images/gallery/bzp1256.jpg', alt: 'Valley trail' },
  { path: '/images/gallery/bzp1257.jpg', alt: 'Aspen adventure' },
  { path: '/images/gallery/bzp1290.jpg', alt: 'Outdoor experience' },
  { path: '/images/gallery/bzp1293.jpg', alt: 'Mountain scenery' },
  { path: '/images/gallery/bzp1297.jpg', alt: 'Rocky Mountain trail' },
  { path: '/images/gallery/bzp1308.jpg', alt: 'Adventure in Aspen' },
  { path: '/images/gallery/bzp1312.jpg', alt: 'Mountain view' },
  { path: '/images/gallery/bzp1316.jpg', alt: 'Wilderness adventure' },
  { path: '/images/gallery/bzp1330.jpg', alt: 'Scenic overlook' },
  { path: '/images/gallery/bzp1339.jpg', alt: 'Mountain expedition' },
  { path: '/images/gallery/bzp1341.jpg', alt: 'Alpine adventure' },
  { path: '/images/gallery/bzp1375.jpg', alt: 'Mountain trail view' },
  { path: '/images/gallery/bzp1387.jpg', alt: 'Valley adventure' },
  { path: '/images/gallery/bzp1390.jpg', alt: 'Rocky Mountain landscape' },
  { path: '/images/gallery/bzp1393.jpg', alt: 'Aspen wilderness' },
  { path: '/images/gallery/bzp1398.jpg', alt: 'Mountain scenery' },
  { path: '/images/gallery/bzp1411.jpg', alt: 'Outdoor adventure' },
  { path: '/images/gallery/bzp1450.jpg', alt: 'Mountain expedition' },
  { path: '/images/gallery/bzp1456.jpg', alt: 'Valley landscape' },
  { path: '/images/gallery/bzp1476.jpg', alt: 'Adventure experience' },
  { path: '/images/gallery/bzp1501.jpg', alt: 'Mountain vista' },
  { path: '/images/gallery/bzp1511.jpg', alt: 'Aspen outdoor experience' },
  { path: '/images/gallery/bzp1520.jpg', alt: 'Trail adventure' },
  { path: '/images/gallery/bzp1523.jpg', alt: 'Mountain view' },
  { path: '/images/gallery/bzp1525.jpg', alt: 'Rocky Mountain adventure' },
  { path: '/images/gallery/bzp1543.jpg', alt: 'Wilderness trail' },
  { path: '/images/gallery/bzp1550.jpg', alt: 'Scenic mountain' },
  { path: '/images/gallery/bzp1553.jpg', alt: 'Adventure moment' },
  { path: '/images/gallery/bzp1555.jpg', alt: 'Mountain landscape' },
  { path: '/images/gallery/bzp1570.jpg', alt: 'Valley panorama' },
  { path: '/images/gallery/bzp1573.jpg', alt: 'Aspen mountain' },
  { path: '/images/gallery/bzp1599.jpg', alt: 'Outdoor scenery' },
  { path: '/images/gallery/bzp1611.jpg', alt: 'Mountain adventure' },
  { path: '/images/gallery/bzp1617.jpg', alt: 'Trail experience' },
  { path: '/images/gallery/bzp1643.jpg', alt: 'Rocky Mountain view' },
  { path: '/images/gallery/bzp1647.jpg', alt: 'Mountain expedition' },
  { path: '/images/gallery/bzp1666.jpg', alt: 'Wilderness adventure' },
  { path: '/images/gallery/bzp1681.jpg', alt: 'Aspen trail' },
  { path: '/images/gallery/bzp1691.jpg', alt: 'Mountain landscape' },
  { path: '/images/gallery/bzp1697.jpg', alt: 'Valley adventure' },
  { path: '/images/gallery/bzp1717.jpg', alt: 'Mountain scenery' },
  { path: '/images/gallery/bzp1740.jpg', alt: 'Adventure in the Rockies' },
  { path: '/images/gallery/bzp1755.jpg', alt: 'Alpine meadow view' },
  { path: '/images/gallery/bzp1771.jpg', alt: 'Mountain adventure' },
  { path: '/images/gallery/bzp1777.jpg', alt: 'Scenic Rocky Mountains' },
  { path: '/images/gallery/bzp1792.jpg', alt: 'Aspen wilderness experience' },
]

// RVA FAQ data for seeding
export const rvaFaqs = [
  { q: 'How much does a guided fly fishing trip in Aspen cost?', a: 'Guided fly fishing trips with Rich Valley Adventures typically range from $150–$350 per person depending on trip length (half-day or full-day) and group size. All gear, licenses, and instruction are included. Call us at 970-456-3666 for current pricing and availability.' },
  { q: 'What is included in a Rich Valley Adventures guided trip?', a: 'Every trip includes expert local guides, all necessary gear and equipment, safety briefings, and transportation to the activity location. For fly fishing: rods, reels, waders, boots, and flies. For mountain biking: bikes and helmets. Groups are kept to 2–6 guests per guide for a truly personalized experience.' },
  { q: 'What is the best time of year for fly fishing in the Roaring Fork Valley?', a: 'Peak fly fishing season in the Roaring Fork Valley near Aspen runs July through September, when the river is lower and clearer. The full season runs May–October. Spring runoff (April–June) can make the river high and murky. Certain Gold Medal stretches are fishable year-round.' },
  { q: 'Do I need prior experience for paddle boarding or mountain biking?', a: "No experience is required for any of our adventures. Our certified guides provide complete instruction, and we select terrain appropriate for each group's ability level. All ages and fitness levels are welcome. Private instruction is available for complete beginners." },
  { q: 'How small are Rich Valley Adventures guided groups?', a: 'We keep groups intentionally small — typically 2 to 6 guests per guide. We do not run large group tours. Private and semi-private bookings are available for families, couples, and corporate groups. Small groups are central to the quality and safety of every experience.' },
  { q: 'What outdoor adventures are available near Aspen in summer?', a: 'Rich Valley Adventures offers 7 guided outdoor experiences near Aspen from May through October: fly fishing on the Roaring Fork River, stand-up paddle boarding on mountain lakes, mountain biking on singletrack trails, guided hiking in the Elk Mountains, scenic private Escalade tours, horseback riding, and elevated camping.' },
  { q: 'Is fly fishing legal on the Roaring Fork River near Aspen?', a: 'Yes. The Roaring Fork River and many tributaries near Aspen are designated Gold Medal trout waters open to fly fishing with a valid Colorado license. Rich Valley Adventures handles all licensing as part of guided trips — guests do not need to obtain a license separately.' },
  { q: 'Where is Rich Valley Adventures based and what areas do you serve?', a: 'We are based in Aspen, Colorado (81611) and guide adventures throughout the Roaring Fork Valley, including Aspen, Snowmass Village, Basalt, and Carbondale. Rich Valley Adventures was founded in 2012 by local outdoor professionals who grew up in the valley.' },
]

export const alpenglowFaqs = [
  { q: 'How much does a limo from Aspen to Denver airport cost?', a: 'A private luxury transfer from Aspen, Colorado to Denver International Airport (DEN) is approximately 3.5–4 hours each way. Pricing varies based on vehicle, time of day, and group size. Call us at 970-456-3666 for a custom quote. We serve Denver (DEN), Eagle (EGE), and Aspen (ASE) airports.' },
  { q: 'Do you offer airport pickup at Aspen/Pitkin County Airport (ASE)?', a: 'Yes. We provide meet-and-greet pickup service at Aspen/Pitkin County Airport (ASE). We track your flight in real time and adjust for early arrivals or delays. Our chauffeurs assist with luggage and provide seamless door-to-door service to any destination in Aspen or the Roaring Fork Valley.' },
  { q: "What's the best way to get from Eagle/Vail airport to Aspen?", a: 'The most comfortable option is a private car service. Eagle County Regional Airport (EGE) is approximately 70 miles from Aspen via I-70 and Highway 82 — about 1.5 to 2 hours depending on conditions. Aspen Alpenglow Limousine offers direct, door-to-door luxury transfers from Eagle airport to any Aspen destination.' },
  { q: 'How far in advance should I book a limousine in Aspen?', a: 'We recommend booking 48–72 hours in advance for standard transfers. For weddings, corporate events, or peak seasons (ski season December–March and summer July–August), book 2–4 weeks ahead. Last-minute bookings are occasionally available — call 970-456-3666 to check.' },
  { q: 'Do you offer wedding transportation in Aspen?', a: 'Yes. We specialize in wedding transportation throughout Aspen and Snowmass, Colorado. We provide bridal party transfers, venue logistics, and guest shuttle coordination. Both our Escalade and Sprinter van are available. We work closely with wedding planners to ensure a flawless, elegant experience.' },
  { q: 'Is Aspen Alpenglow Limousine available 24 hours a day?', a: 'Yes. We operate 24/7/365 — including early-morning departures, late-night arrivals, and overnight transfers to Denver. Call 970-456-3666 at any hour for assistance.' },
  { q: 'Can you transport groups to ski resorts from Aspen?', a: 'Absolutely. We provide private group transportation to Aspen Mountain, Aspen Highlands, Buttermilk, Snowmass ski resort, and other destinations throughout the Roaring Fork Valley. Our Luxury Sprinter van seats up to 14 passengers — ideal for ski groups.' },
  { q: 'What vehicles does Aspen Alpenglow Limousine use?', a: 'Our fleet includes a black Executive Cadillac Escalade (up to 6 passengers) and a black Luxury Mercedes Sprinter van (up to 14 passengers). Both feature premium leather interiors, climate control, and complimentary amenities. All vehicles are late-model, meticulously maintained, and professionally chauffeured.' },
]
